<?php

namespace TrustedForms;

require_once 'autoload.php';

/**
 * Test class for ValidationChainItem.
 * Generated by PHPUnit on 2011-03-19 at 10:58:37.
 */
class FormValidatorTest extends \PHPUnit_Framework_TestCase
{
    public function testFlag()
    {
        $form = new FormValidator;
        $form->setFlag('mark');
        $form->setFlag('flag','value');
        $this->assertTrue($form->isFlag('mark'));
        $this->assertFalse($form->isFlag('none'));
        $this->assertTrue($form->isFlag('flag'));
        $this->assertEquals('value', $form->getFlag('flag'));
    }

    public function testSetFlags()
    {
        $form = new FormValidator;
        $form->setFlags(array('f1'=>'a','f2'=>'b'));
        $this->assertTrue($form->isFlag('f1'));
        $this->assertEquals('a', $form->getFlag('f1'));
        $this->assertTrue($form->isFlag('f2'));
        $this->assertEquals('b', $form->getFlag('f2'));
    }

    public function testArrayValidator()
    {
        $form = new FormValidator;
        $form['key'] = new VariableValidator();
        $err = new FormErrorReporter('msg');
        $err->addFlag('flg');
        $form['key']->addReporter($err);
        $form['key']->addToChain(new \TrustedForms\ValueChecks\IsNumeric());
        $this->assertFalse($form->checkArray(array('key'=>'value')));
        $this->assertTrue($form->isFlag('flg'));
    }
}
