<?php

namespace TrustedForms;

require_once 'autoload.php';

/**
 * Test class for ValidationChainItem.
 * Generated by PHPUnit on 2011-03-19 at 10:58:37.
 */
class FormErrorReporterTest extends \PHPUnit_Framework_TestCase
{
    public function testFlags()
    {
        $r = new FormErrorReporter('message');
        $r->addFlag('flag 1');
        $r->addFlag('flag 2');
        $r->addFlag('flag 3');

        $this->assertEquals(
                array('flag 1'=>'message','flag 2'=>'message','flag 3'=>'message'),
                $r->getFlags()
        );

    }
}
