<?php

namespace TrustedForms;

require_once 'autoload.php';

/**
 * Test class for ValidationChainItem.
 * Generated by PHPUnit on 2011-03-19 at 10:58:37.
 */
class FormValidatorTest extends \PHPUnit_Framework_TestCase
{
    public function testFlags()
    {
        $form = new FormValidator;
        $form->setFlag('mark');
        $this->assertTrue($form->isFlag('mark'));
        $this->assertFalse($form->isFlag('none'));
    }

    public function testMultipleFlags()
    {
        $form = new FormValidator;
        $form->setFlag(array('f1','f2'));
        $this->assertTrue($form->isFlag('f1'));
        $this->assertTrue($form->isFlag('f2'));
    }

    public function testArrayValidator()
    {
        $form = new FormValidator;
        $form['key'] = new VariableValidator();
        $err = new FormErrorReporter('msg');
        $err->addFlag('flg');
        $form['key']->addReporter($err);
        $form['key']->addToChain(new \TrustedForms\ValueChecks\IsNumeric());

        
        $this->assertFalse($form->checkArray(array('key'=>'value')));
        \var_dump($form);
        $this->assertTrue($form->isFlag('flg'));
    }
}
